"""add_diferencia_and_comentarios_to_balance

Revision ID: b3ec69ff5d9c
Revises: 1ce331264aa0
Create Date: 2025-10-02 23:35:57.271763+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ec69ff5d9c'
down_revision: Union[str, None] = '1ce331264aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('balance', sa.Column('comentarios', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'comentarios')
    op.drop_column('balance', 'diferencia')
    # ### end Alembic commands ###
